# Data Science Libraries

## Numpy

In [2]:
# Importing Modules 
import numpy as np 

In [20]:
arr = np.array([2,3,4,5])
arr
print(arr)

[2 3 4 5]


In [21]:
l = [22,67,90,45]
print(np.array(l))

[22 67 90 45]


### 1D array

In [22]:
arr

array([2, 3, 4, 5])

In [23]:
arr[1:]

array([3, 4, 5])

In [24]:
l = [[3,3,5], [35,27,42]]
arr_2d = np.array(l)
arr_2d

array([[ 3,  3,  5],
       [35, 27, 42]])

In [25]:
arr_2d[1,1]

27

In [26]:
arr_np = np.array([
                  [10,11,12,13],
                  [20,21,22,23],
                  [30,31,32,33],
                  [40,41,42,43],
                  [50,51,52,53]
                  ])

In [27]:
arr_np.shape

(5, 4)

In [3]:
np.arange(2,23)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22])

In [6]:
arr = np.arange(1,11)
arr.dtype

dtype('int64')

### Identity Numpy Formation

In [15]:
Identity = np.eye(5,dtype='int64')
Identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [11]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Numpy Array Containing Zeros 

In [12]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Numpy Ones Formation 

In [14]:
np.ones((4,4),dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### Numpy Array  containing diagonal Elements

In [16]:
np.diag([2,34,36,43])

array([[ 2,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 36,  0],
       [ 0,  0,  0, 43]])

In [18]:
np.random.rand(3)

array([0.40597537, 0.57663087, 0.98396712])

In [19]:
np.random.randn(5)

array([ 0.68106086, -1.73378422,  0.44231799,  1.22056693,  0.78176424])

In [23]:
arr1 = np.random.randint(10,50,10)
arr1

array([29, 43, 34, 23, 41, 40, 26, 22, 42, 18])

In [21]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Values of Min and Max Elements 

In [25]:
arr1.min()

18

In [26]:
arr1.max()

43

## Indexes of Min and Max Elements in Array 

In [27]:
arr1.argmin()

9

In [29]:
arr1.argmax()

1

In [30]:
np.linspace(1,10,7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

## Broad Casting 

In [48]:
arr = np.random.randint(10,50,30).reshape(6,5)

In [50]:
arr


array([[49, 33, 11, 49, 31],
       [47, 28, 12, 23, 21],
       [23, 19, 48, 22, 41],
       [14, 25, 45, 14, 13],
       [31, 37, 46, 28, 16],
       [46, 11, 37, 48, 18]])

### Array Indexing 

In [47]:
arr[1:3,3:]

array([[33, 49],
       [26, 38]])

In [34]:
arr = np.arange(5)
arr[-1]

4

In [53]:
arr[0:3:2,0::2]

array([[49, 11, 31],
       [23, 48, 41]])